Restoring web3j-cli
web3j/web3j-cli pull request #50
Opened 2020-12-15 22:45 UTC by AlexandrouR

2020-12-21 19:34 UTC, SweeXordious requested changes
Looks good in general. Simple changes need to be addressed. 
Also, might be useful to take a look on: https://velocity.apache.org/

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/Dockerfile.template
> +# To run the generated image execute: `docker run --env EPIRUS_LOGIN_TOKEN="<your login token>" web3app`
should be `WEB3J_` prefix

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/Dockerfile.template
> +ENTRYPOINT ["/root/.epirus/epirus", "run", "rinkeby"]
use `.web3j.` folder

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/Java.template
> +    private static final boolean epirusDeploy = Boolean.parseBoolean(System.getenv().getOrDefault("EPIRUS_DEPLOY", "false"));
we no longer have this

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/Java.template
> +    }
we no longer use the epirus infrastructure

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/Java.template
> +    }
I think the code can be simplifed in the whole template more. 
This is an example of how a Java template can look like:
```
package org.web3j;

import org.web3j.crypto.Credentials;
import org.web3j.crypto.WalletUtils;
import org.web3j.generated.contracts.HelloWorld;
import org.web3j.protocol.Web3j;
import org.web3j.protocol.http.HttpService;
import org.web3j.tx.gas.DefaultGasProvider;

/**
 * <p>This is the generated class for <code>web3j new helloworld</code></p>
 * <p>It deploys the Hello World contract in src/main/solidity/, prints its address then call the greeting method</p>
 */
public class Web3App {
    private static final String walletPassword = System.getenv().getOrDefault("WEB3J_WALLET_PASSWORD", "");;
    private static final String walletPath = System.getenv("WEB3J_WALLET_PATH");
    private static final String nodeUrl = System.getenv().getOrDefault("WEB3J_NODE_URL", System.getProperty("WEB3J_NODE_URL"));

    public static void main(String[] args) throws Exception {
        Credentials credentials = WalletUtils.loadCredentials(walletPassword, walletPath);
        Web3j web3j = Web3j.build(new HttpService(nodeUrl));

        System.out.println("Deploying HelloWorld contract ...");
        HelloWorld helloWorld = HelloWorld.deploy(web3j, credentials, new DefaultGasProvider(), "Hello Blockchain World!").send();

        System.out.println("Contract address: " + helloWorld.getContractAddress());
        System.out.println("Greeting method result: " + helloWorld.greeting().send());
    }
}
```
A Kotlin equivalent should be written for the kotlin template.
Should be discussed more.

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/Kotlin.template
> + * <p>For more information on how to run this project, please refer to our <a href="https://docs.epirus.io/quickstart/#deployment">documentation</a></p>
same as previous comment

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/README.openapi.md
> +This is a generated [Web3j-OpenAPI](https://docs.web3j.io/web3j_openapi) project using the [Epirus-CLI](https://docs.epirus.io/).
using `Web3j-CLI`

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/README.openapi.md
> +```
I think we no longer are able to run the project directly

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/build.gradle.template
>      main.kotlin.srcDirs += "${web3j.generatedFilesBaseDir}/main/java"
I think this can be removed as they are the default values for the gradle plugin

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/build.gradleImport.template
>  sourceSets {
same as previous

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/build.gradleImportJava11.template
> +}
same as previous

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/build.gradleJava11.template
>  }
same

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/erc20/JavaErc20.template
> +package <package_name>;
template should be simplified

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/erc20/build.gradleErc20.template
> +}
these are default values, no need to put them

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/erc20/build.gradleErc20Java11.template
> +}
Same

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/erc777/JavaErc777.template
> +package <package_name>;
To be simplified

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/erc777/README.erc777.md
> +This is a generated ERC777 project using the [Epirus-CLI](https://docs.epirus.io/).
web3j-cli

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/erc777/README.erc777.md
> +```
to be removed, I think

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/erc777/build.gradleErc777.template
> +}
same

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/erc777/build.gradleErc777Java11.template
> +}
same

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/erc777/build.gradleErc777Java11.template
> +            "io.epirus:epirus-web3j:$web3jEpirusVersion"
we no longer need this one

2020-12-21 19:34 UTC, SweeXordious commented on src/main/resources/project/erc777/build.gradleErc777Java11.template
> +    web3jEpirusVersion = '0.0.7'
we no longer need this one

2020-12-21 19:34 UTC, SweeXordious commented on src/test/java/org/web3j/console/docker/DockerCommandTest.java
> +import org.junit.jupiter.api.*;
is this not flagged by spotless ?

2020-12-21 19:34 UTC, SweeXordious commented on src/test/java/org/web3j/console/project/InteractiveOptionsTest.java
> +import java.io.*;
spotless ?

2020-12-21 19:34 UTC, SweeXordious commented on src/test/java/org/web3j/console/wallet/WalletUpdateCommandTest.java
> +import static org.mockito.Mockito.*;
spotless ?

2020-12-21 19:34 UTC, SweeXordious commented on src/test/resources/project/Dockerfile.template
> +# To run the generated image execute: `docker run --env EPIRUS_LOGIN_TOKEN="<your login token>" web3app`
WEB3J

2020-12-21 19:34 UTC, SweeXordious commented on src/test/resources/project/Dockerfile.template
> +	&& /root/.epirus/epirus \
.web3j

2020-12-21 19:34 UTC, SweeXordious commented on src/test/resources/project/Dockerfile.template
> +ENTRYPOINT ["/root/.epirus/epirus", "run", "rinkeby"]
we no longer have this, I think

2020-12-21 19:34 UTC, SweeXordious commented on src/test/resources/project/EmptyJava.template
> +
maybe we should add some java docs : `this class was generated by ...`

2020-12-21 19:34 UTC, SweeXordious commented on src/test/resources/project/EmptyKotlin.template
> +
same

2020-12-21 19:34 UTC, SweeXordious commented on src/test/resources/project/Java.template
> +package <package_name>;
To be simplified. Also, why do we have two template directories ? one in `main` and one in `test` ?

2020-12-21 19:34 UTC, SweeXordious commented on src/test/resources/project/Kotlin.template
> +
same

2020-12-21 19:34 UTC, SweeXordious commented on src/test/resources/project/README.openapi.md
> +# OpenAPI project
same

2020-12-21 19:34 UTC, SweeXordious commented on src/test/resources/project/build.gradle.template
> +plugins {
again, why do we have duplicated files ? between `main` and `test` ?

2020-12-22 07:43 UTC, AlexandrouR commented on src/main/java/org/web3j/console/project/utils/ProjectUtils.java
> +                                "https://" + network.getNetworkName() + ".api.epirus.io/metadata");
Moved to epirus-cli

2020-12-22 08:21 UTC, AlexandrouR commented on src/main/java/org/web3j/console/project/utils/ProjectUtils.java
> +                                "https://" + network.getNetworkName() + ".api.epirus.io/metadata");
Moved to epirus cli

2020-12-22 08:21 UTC, AlexandrouR commented on src/main/java/org/web3j/console/SubCommand.java
> +    }
Removed it

2020-12-22 08:23 UTC, AlexandrouR commented on src/main/java/org/web3j/console/docker/subcommands/DockerRunCommand.java
> +    String deployNetwork;
Docker run was moved to epirus

2020-12-22 08:23 UTC, AlexandrouR commented on src/main/resources/project/Dockerfile.template
> +ENTRYPOINT ["/root/.epirus/epirus", "run", "rinkeby"]
Docker was moved to epirus

2020-12-22 08:27 UTC, AlexandrouR commented on src/main/resources/project/README.openapi.md
> +This is a generated [Web3j-OpenAPI](https://docs.web3j.io/web3j_openapi) project using the [Epirus-CLI](https://docs.epirus.io/).
fixed

2021-01-11 00:41 UTC, merged

2021-05-16 20:00 UTC, edaj965 commented
> Se ve bien en general. Es necesario abordar cambios simples.
> Además, podría ser útil echarle un vistazo a: https://velocity.apache.org/